/**
 * Tokens remapeados a la paleta Supabase-dark de code.html (y DESIGN.md alpha).
 * Se conservan los nombres de clave M3 para re-skinnear TopBar/Sidebar/Admin sin
 * tocar esos archivos, más los nuevos `ink`/`edge-soft` que el marcado necesita.
 *
 * ponytail: hex fijos (no variables CSS). El stash del modo claro espera
 * rgb(var(--c-*)); al re-aplicarlo habrá conflicto y se reconcilia a mano.
 * Upgrade path: migrar colors a `rgb(var(--c-*) / <alpha-value>)` + :root/html.light.
 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx}'
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#282828',
        'surface-container-lowest': '#121212',
        'surface-container-low': '#1c1c1c',
        'surface-container': '#202020',
        'surface-container-high': '#242424',
        'surface-container-highest': '#333333',
        'surface-variant': '#333333',
        'on-surface': '#ededed',
        'on-surface-variant': '#8e8e8e',
        'inverse-surface': '#ededed',
        'inverse-on-surface': '#171717',
        'outline': '#8e8e8e',
        'outline-variant': '#333333',
        'surface-tint': '#3ecf8e',
        'primary': '#3ecf8e',
        'on-primary': '#171717',
        'primary-container': '#4ade80',
        'on-primary-container': '#171717',
        'inverse-primary': '#24b47e',
        'secondary': '#a1a1a1',
        'on-secondary': '#171717',
        'secondary-container': '#474746',
        'on-secondary-container': '#a1a1a1',
        'tertiary': '#ffdb13',
        'on-tertiary': '#171717',
        'tertiary-container': '#ffdb13',
        'on-tertiary-container': '#171717',
        'error': '#ff5f56',
        'on-error': '#171717',
        'error-container': '#ff2201',
        'on-error-container': '#ededed',
        'primary-fixed': '#4ade80',
        'primary-fixed-dim': '#3ecf8e',
        'on-primary-fixed': '#171717',
        'on-primary-fixed-variant': '#171717',
        'secondary-fixed': '#ededed',
        'secondary-fixed-dim': '#a1a1a1',
        'on-secondary-fixed': '#171717',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed': '#ffdb13',
        'tertiary-fixed-dim': '#ffdb13',
        'on-tertiary-fixed': '#171717',
        'on-tertiary-fixed-variant': '#171717',
        'background': '#131313',
        'on-background': '#ededed',
        'hairline': '#2e2e2e',
        'hairline-strong': '#383838',
        'ink': '#171717',
        'edge-soft': '#282828',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'gutter': '1.5rem',
        'gutter-desktop': '1.5rem',
        'margin': '2rem',
        'margin-desktop': '2rem',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'body': ['Manrope', 'sans-serif'],
        'mono': ['Source Code Pro', 'monospace'],
        'display': ['Inter'],
        'headline-sm': ['Inter'],
        'label-code': ['Source Code Pro'],
        'caption': ['Manrope'],
        'body-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'body-sm': ['Manrope'],
        'headline-xl-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-md': ['Inter'],
        'title-md': ['Inter'],
        'title-lg': ['Inter'],
        'mono-sm': ['Source Code Pro'],
        'mono-md': ['Source Code Pro'],
        'mono-lg': ['Source Code Pro'],
        'label-caps': ['Source Code Pro'],
      },
      fontSize: {
        'display': ['28px', { lineHeight: '34px', letterSpacing: '-0.42px', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '25px', fontWeight: '500' }],
        'label-code': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'caption': ['13px', { lineHeight: '19px', fontWeight: '400' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '32px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '40px', letterSpacing: '-0.035em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '28px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'mono-lg': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'mono-md': ['12px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '500' }],
      }
    }
  },
  plugins: []
};
