/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx}'
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353943',
        'surface-container-lowest': '#0a0e17',
        'surface-container-low': '#181b25',
        'surface-container': '#1c1f29',
        'surface-container-high': '#262a34',
        'surface-container-highest': '#31353f',
        'surface-variant': '#31353f',
        'on-surface': '#dfe2ef',
        'on-surface-variant': '#bbcabf',
        'inverse-surface': '#dfe2ef',
        'inverse-on-surface': '#2c303a',
        'outline': '#86948a',
        'outline-variant': '#3c4a42',
        'surface-tint': '#4edea3',
        'primary': '#4edea3',
        'on-primary': '#003824',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'inverse-primary': '#006c49',
        'secondary': '#4cd7f6',
        'on-secondary': '#003640',
        'secondary-container': '#03b5d3',
        'on-secondary-container': '#00424e',
        'tertiary': '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#e29100',
        'on-tertiary-container': '#523200',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        'background': '#0f131c',
        'on-background': '#dfe2ef',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'gutter': '1rem',
        'gutter-desktop': '1.25rem',
        'margin': '1rem',
        'margin-desktop': '1.5rem',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter'],
        'headline-xl-mobile': ['Inter'],
        'mono-sm': ['JetBrains Mono'],
        'label-caps': ['JetBrains Mono'],
        'mono-md': ['JetBrains Mono'],
        'mono-lg': ['JetBrains Mono'],
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-md': ['Inter'],
        'title-md': ['Inter'],
        'title-lg': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-xl-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'mono-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
        'mono-md': ['12px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'title-lg': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      }
    }
  },
  plugins: []
};
